Repository numlinalg/RLinearAlgebra.jl, pull requests merged in 2025-01, with the labels that each got.

#77 Separating Modified Gram Schmidt, Arnoldi, and Randomized Arnoldi
  docs/src/api/linear_solver_helpers.md
  src/linear_solver_routines.jl
  src/linear_solver_routines/krylov_helpers/arnoldi.jl
  src/linear_solver_routines/krylov_helpers/modified_gram_schmidt.jl
  src/linear_solver_routines/krylov_helpers/randomized_arnoldi.jl
  test/linear_solver_routines/krylov_helpers/proc_arnoldi.jl
  test/linear_solver_routines/krylov_helpers/proc_modified_gram_schmidt.jl
  test/linear_solver_routines/krylov_helpers/proc_randomized_arnoldi.jl
  test/testgroups.txt
Labels: enhancement

#76 Developer Documents
  docs/make.jl
  docs/src/dev/checklists.md
  docs/src/dev/contributing.md
  docs/src/dev/styleguide.md
Labels: documentation

#78 Distribution by frobenius norm over rows or columns of a matrix
  docs/src/api/linear_samplers.md
  docs/src/api/linear_solver_helpers.md
  src/linear_samplers.jl
  src/linear_samplers/linear_sampler_helpers/induced_distributions/frobenius_norm.jl
  src/linear_samplers/vec_row_prop_to_norm_replace.jl
  src/linear_solver_routines/krylov_helpers/modified_gram_schmidt.jl
  test/linear_samplers/proc_vec_row_prop_to_norm_replace.jl
  test/linear_samplers/sampler_helpers/induced_distributions/proc_frobenius_norm.jl
  test/testgroups.txt
Labels: documentation, enhancement
